version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tourwithease-redis
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
    - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: tourwithease-postgres
    environment:
      POSTGRES_DB: tourwithease
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpassword
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: tourwithease-api
    ports:
    - "8000:8000"
    environment:
    - NODE_ENV=development
    - REDIS_URL=redis://redis:6379
    - DATABASE_URL=postgresql://developer:devpassword@postgres:5432/tourwithease
    depends_on:
    - redis
    - postgres
    volumes:
    - ./backend/api-gateway:/app
    - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tourwithease-frontend
    ports:
    - "3000:3000"
    environment:
    - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
    - ./frontend:/app
    - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
