# Agent Basic Configuration
name: "trip_orchestrator_agent"
model: "gemini-2.0-flash"
port: 8001
version: "1.0.0"
description: |
  Master trip orchestrator that coordinates all travel planning aspects including
  flights, hotels, context, pricing, and bookings across multiple specialist agents.

# Model Configuration
model_config:
  temperature: 0.2
  top_p: 0.8
  max_output_tokens: 3000
  
# Safety Settings
safety_settings:
  - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_HARASSMENT" 
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_HATE_SPEECH"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"

# Agent Instruction
instruction: |
  You are the Trip Orchestrator Agent - the master coordinator for comprehensive travel planning.
  
  **Your Primary Role**: COORDINATE, don't duplicate specialist work
  
  **Coordination Process**:
  1. **Analyze** user requests to understand travel needs
  2. **Select** appropriate specialist agents (Flight, Hotel, Context specialists)
  3. **Coordinate** parallel requests to multiple agents
  4. **Synthesize** responses into comprehensive travel plans
  5. **Present** unified recommendations to users
  
  **Agent Coordination**:
  - Flight Specialist: For flight searches, pricing, and aviation expertise
  - Hotel Specialist: For accommodation searches and hospitality guidance
  - Context Specialist: For weather, currency, and cultural information
  
  **Your Value-Add**:
  - Intelligent agent selection based on user needs
  - Parallel coordination for efficiency
  - Cross-domain synthesis (combining flights + hotels + context)
  - Comprehensive trip planning that no single specialist can provide
  - Conflict resolution between different agent recommendations
  
  **Do NOT**:
  - Duplicate work that specialists do better
  - Provide detailed flight/hotel search results directly
  - Make specific bookings without specialist input
  
  **DO**:
  - Coordinate specialists efficiently
  - Synthesize multiple agent responses
  - Provide high-level trip planning guidance
  - Handle complex multi-component trip requests

# Capabilities
capabilities:
  - "trip_planning"
  - "agent_coordination"
  - "price_analysis"
  - "booking_management"
  - "travel_recommendations"
  - "multi_agent_orchestration"
  - "comprehensive_travel_solutions"

# Specialist Agents Configuration
specialist_agents:
  flight_specialist:
    url: "http://localhost:8003"
    capabilities: ["flight_search", "price_analysis", "flight_recommendations"]
    timeout: 30.0
  hotel_specialist:
    url: "http://localhost:8004" 
    capabilities: ["hotel_search", "accommodation_analysis", "hotel_recommendations"]
    timeout: 30.0
  context_specialist:
    url: "http://localhost:8002"
    capabilities: ["weather_info", "currency_info", "cultural_insights"]
    timeout: 20.0

coordination:
  max_parallel_agents: 5
  default_timeout: 30.0
  retry_attempts: 2
  fallback_strategy: "graceful_degradation"

# Metadata
metadata:
  orchestration_capabilities: true
  multi_agent_coordination: true
  aws_integration: true
  specializations:
    - "trip_planning"
    - "agent_coordination"
    - "travel_orchestration"
    - "booking_management"
  author: "Google ADK Team"
